Millie remove thanks for completing -> change to blank page
Watts-Lab/surveys pull request #135
Opened 2023-05-24 17:43 UTC by gumillie222

json files + tests + instructions updates
#127

2023-05-25 14:12 UTC, JamesPHoughton requested changes
Just a weird issue with a bunch of new screenshots being added to the repo. Lets get rid of those, and then ready to merge.

2023-05-25 14:12 UTC, JamesPHoughton commented on cypress/screenshots/surveys/lonelinessSingleItem/lonelinessSingleItem.cy.jsx/autonomyNeedSatisfaction/screenshot.png
If none of the testing code changed, this might be something caused by a new version of cypress. The easiest way to avoid committing all these to github would probably be to add `cypress/screenshots` to the .gitignore

2023-05-25 16:43 UTC, gumillie222 commented
I realized there are still extra screen shots so currently looking into why

2023-05-25 17:17 UTC, gumillie222 commented
Still not sure where the extra screenshots came from. I deleted the screenshots from the cypress/screenshots folder and ran some tests and there were no new screenshots coming up in the folder. Ready for review

2023-06-25 08:02 UTC, JamesPHoughton approved these changes

2023-07-17 13:38 UTC, merged